### ISSUE TITLE
Database Schema Review

### ISSUE THREAD

**Issue by BCrawfordScott** [sam-hearst/Comic-collection#1]
Great work team!  Simple is always best.  A couple of notes:

- [x] Add createdAt and updatedAt to all tables
- [x] Remove `Default Shelves`
- [x] Change `Custom Shelves` to just `Shelves` 
   - "Default" shelves are not different than regular shelves, they are just created at the same time that the user is created so that everyone has them. No need to create a separate table for them.
- [x] Add a comic image url to your `Comic Books` table. You'll want to have the cover visible and you'll need to save that in the database.  You can allow it to be null and use a default image if you don't have a url for the comic.

Keep up the good work!

**Comment by dornkholland** [comment]
Thanks for reviewing our code.  We would like to discuss our default shelves implementation further before deleting it as it is our implementation of one of our MVP's, and if you do suggest to remove it we'd like a bit of assistance as to how we should implement the read status MVP.

**Comment by BCrawfordScott** [comment]
For sure!  Consider this: what if every time a new user was registered, we automatically created 3 "default" shelves for them as well with predetermined names of "Read", "Reading", "Want to Read"? That way you get your default book shelves AND the read status of a book is determined by the shelf it is in?

**Comment by KevKodes** [comment]
That definitely makes sense and our original schema had just a single shelves table. We went back and forth debating the best way to ensure that there is only a single read status on a book for any user. We thought separating the shelves could help keep our querying and routing clean when changing the read status of a book. It sounds like you are saying it is more important to keep the database schema organized than it is the querying?

**Comment by dornkholland** [comment]
Thanks for your help @BCrawfordScott !  We have updated our database schema to fix the issues outlined above.  
https://drawsql.app/3headmonkeynyc/diagrams/comic-shelf-db-final-v1-0#
