### ISSUE TITLE
Add basic functionality for reviews

### ISSUE THREAD

**Issue by KevKodes** [sam-hearst/Comic-collection#34]
Run through sequelize to add the reviews table to the db. Basic routing for the reviews table.

- [ ] make it ajax!!

**Comment by dornkholland** [comment]
Completed databasing and querying for reviews, **need ajax routes completed for posting/edting/deleting reviews**.  I Will work on front end buttons for that functionality, @sam-hearst  Just assume those buttons are there for when querying by id/class in javascript.
