### ISSUE TITLE
navbar routes

### ISSUE THREAD

**Issue by sam-hearst** [sam-hearst/Comic-collection#43]
As a first-time user who just wants to demo Comic Collection, I want to be able to try out the site with a demo user login via a single button click on the login and signup form, so that I can access Comic Collection without having to go through the trouble of creating a new account.

**Comment by leoworkcp** [comment]
This issue can be deleted is already there!!

**Comment by dornkholland** [comment]
Fixed navbar bug, still working on:
- [ ] implement navbar mycomics route

**Comment by dornkholland** [comment]
Navbar has been fully fixed and configured, further details: https://github.com/sam-hearst/Comic-collection/pull/64
