### ISSUE TITLE
full functionality for reviews: adding, deleting, and editing (all through AJAX)

### ISSUE THREAD

**Issue by sam-hearst** [sam-hearst/Comic-collection#72]

**Comment by dornkholland** [comment]
- [ ] Ajax add reviews: https://github.com/sam-hearst/Comic-collection/pull/79
- [ ] Ajax delete reviews
- [ ] Ajax edit reviews

**Comment by dornkholland** [comment]
https://github.com/sam-hearst/Comic-collection/pull/82/
